naveen.out : add.o sub.o mul.o div.o cal.o
	gcc -o naveen.out add.o sub.o div.o mul.o cal.o
add.o :add.c
	gcc -c add.c
sub.o :sub.c
	gcc -c sub.c
mul.o :mul.c
	gcc -c mul.c
div.o :div.c
	gcc -c div.c
cal.o :cal.c
	gcc -c  cal.c
