ass1.out :delete_at_first.o delete_at_last.o delete_list.o find_node.o insert_at_first.o insert_at_last.o sll.o print_list.o
	gcc -o ass1.out delete_at_first.o delete_at_last.o delete_list.o find_node.o insert_at_first.o insert_at_last.o sll.o print_list.o
delete_at_first.o : delete_at_first.c
	gcc -c delete_at_first.c
delete_at_last.o : delete_at_last.c
	gcc -c delete_at_last.c
delete_list.o : delete_list.c
	gcc -c delete_list.c
find_node.o : find_node.c
	gcc -c find_node.c
insert_at_first.o : insert_at_first.c
	gcc -c insert_at_first.c
insert_at_last.o : insert_at_last.c
	gcc -c insert_at_last.c
print_list.o : print_list.c
	gcc -c print_list.c
sll.o : sll.c
	gcc -c sll.c
clean :
	rm *.o *.out