ass3.out: delete_first.o delete_last.o delete_list.o insert_at_first.o insert_at_last.o main.o print_list.o
	gcc -o ass3.out delete_first.o delete_last.o delete_list.o insert_at_first.o insert_at_last.o main.o print_list.o
delete_first.o :delete_first.c
	gcc -c delete_first.c
delete_last.o :delete_last.c
	gcc -c delete_last.c
delete_list.o :delete_list.c
	gcc -c delete_list.c
insert_at_first.o :insert_at_first.c
	gcc -c insert_at_first.c
insert_at_last.o :insert_at_last.c
	gcc -c insert_at_last.c
main.o :main.c
	gcc -c main.c
print_list.o :print_list.c
	gcc -c print_list.c
clean :
	rm *.o  *.out


